In [1]:
import numpy as np

In [2]:
print(np.__version__)
np.show_config()

1.16.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda app\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/anaconda app\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['E:/anaconda app\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'E:/anaconda app\\Library

In [3]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
z=np.zeros((10,10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


In [5]:
%run python-c "import numpy;numpy.info(numpy.add)"

ERROR:root:File `'python-c.py'` not found.


In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
Z = np.arange(10,50)
print(Z)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [9]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:

nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [11]:
Z = np.eye(3)
print(Z)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.84447413 0.11539054 0.48578643]
  [0.47355972 0.61527407 0.01541884]
  [0.4438924  0.9004946  0.57345104]]

 [[0.90848224 0.42038093 0.69463175]
  [0.37098521 0.53235611 0.45010533]
  [0.18301331 0.71821061 0.34492922]]

 [[0.34296737 0.09585039 0.83856432]
  [0.1266426  0.7389117  0.35918662]
  [0.05198084 0.46097733 0.10027318]]]


In [13]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.04425007721195651 0.9996839198625012


In [14]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5816124561301044


In [15]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [18]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [19]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [21]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.73512887  1.24054017 -1.24530476 -0.96209525 -0.87309744]
 [ 1.34753536  0.43243769 -0.85324762  0.3119723  -1.13487099]
 [ 1.34028722  0.08302378 -0.71952178 -0.71242125  0.99438123]
 [ 1.74331411 -0.41862925 -0.14088161 -1.2032052   0.96461238]
 [-1.0914046   0.76184318 -1.36411257 -0.06564585 -0.17063812]]


In [23]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

In [24]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [25]:

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [26]:

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [27]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: Integers to negative integer powers are not allowed.

In [28]:

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


E:\anaconda app\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
E:\anaconda app\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [29]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 8. -1. -6. -1. -4.  5. -2.  2.  1. -9.]


In [30]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[4 5]


In [1]:
# 31

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
 = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

NameError: name 'np' is not defined

In [32]:
np.sqrt(-1) == np.emath.sqrt(-1)

E:\anaconda app\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [33]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

In [34]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [35]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [36]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[3. 8. 2. 5. 9. 1. 7. 8. 0. 1.]
[3. 8. 2. 5. 9. 1. 7. 8. 0. 1.]
[3. 8. 2. 5. 9. 1. 7. 8. 0. 1.]
[3 8 2 5 9 1 7 8 0 1]
[3. 8. 2. 5. 9. 1. 7. 8. 0. 1.]


In [37]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [38]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [39]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [40]:

Z = np.random.random(10)
Z.sort()
print(Z)

[0.14977477 0.15893452 0.27459468 0.42688971 0.43147511 0.43865449
 0.61371831 0.68028605 0.89206576 0.97129016]


In [41]:

Z = np.arange(10)
np.add.reduce(Z)

45

In [42]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [43]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [44]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.39132358 0.44803427 0.57359223 0.60832508 1.02727588 0.90301715
 0.87111515 1.18195998 0.21781877 1.2023549 ]
[1.55016872 0.96071101 0.64180709 1.12335569 0.39855377 1.00979964
 0.79828756 0.73521142 0.85895566 0.89551822]


In [45]:

Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.31602196 0.8430469  0.39596918 0.34071013 0.77107495 0.70481289
 0.66461242 0.23950565 0.84216103 0.        ]


In [46]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [47]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666
3638.1636371179666


In [48]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [49]:

np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [50]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

99


In [51]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [52]:

Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.5213731  0.18315083 0.50959487 0.74162051 0.76557331
  0.51475803 0.48599486 0.46522155 0.74791626]
 [0.5213731  0.         0.48723012 0.07182573 0.24399567 0.35342561
  0.42114697 0.1879357  0.73143922 0.24841056]
 [0.18315083 0.48723012 0.         0.45110101 0.66746619 0.79484333
  0.62003182 0.52018646 0.31194766 0.67458053]
 [0.50959487 0.07182573 0.45110101 0.         0.23283186 0.42245973
  0.47968059 0.25040983 0.67576125 0.23885365]
 [0.74162051 0.24399567 0.66746619 0.23283186 0.         0.42890306
  0.63748891 0.40879049 0.84641001 0.00758375]
 [0.76557331 0.35342561 0.79484333 0.42245973 0.42890306 0.
  0.36689513 0.28055992 1.07068003 0.42629291]
 [0.51475803 0.42114697 0.62003182 0.47968059 0.63748891 0.36689513
  0.         0.2338703  0.9307869  0.6392302 ]
 [0.48599486 0.1879357  0.52018646 0.25040983 0.40879049 0.28055992
  0.2338703  0.         0.80963133 0.41125154]
 [0.46522155 0.73143922 0.31194766 0.67576125 0.84641001 1.07068003
  0.9307869  0.80963

In [53]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [55]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [56]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [57]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [58]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.28052338 -0.12295558 -0.10872455  0.24990814  0.31701594  0.09093335
  -0.00425076 -0.14212388  0.10156538 -0.10084465]
 [ 0.06885169  0.33241493  0.00507353 -0.24544282 -0.0224668  -0.07454661
   0.37281094 -0.01664873 -0.19700436 -0.22304178]
 [ 0.24907842  0.48341976  0.07352471  0.35981026 -0.08034183  0.03046876
  -0.17044642 -0.34862585 -0.26052427 -0.33636353]
 [-0.06889587  0.17195141 -0.19390729  0.235979   -0.26239669  0.01030852
   0.03541073 -0.03955602 -0.10020584  0.21131206]
 [-0.42273734  0.34642434 -0.04578485  0.3795071  -0.29708953  0.15393438
   0.22482385 -0.26231706 -0.29017899  0.2134181 ]]


In [59]:

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[1 3 1]
 [4 4 8]
 [2 9 8]]
[[1 3 1]
 [4 4 8]
 [2 9 8]]


In [60]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [61]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5981681814787


In [62]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [63]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [64]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
np.add.at(Z, I, 1)
print(Z)

[4. 3. 2. 1. 5. 1. 2. 4. 4. 4.]
[7. 5. 3. 1. 9. 1. 3. 7. 7. 7.]


In [65]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [66]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


In [67]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[53 47 54 49]
 [47 70 56 52]
 [50 69 73 48]]
[[53 47 54 49]
 [47 70 56 52]
 [50 69 73 48]]


In [68]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.52199159 0.4685656  0.56839344 0.35650905 0.46572123 0.52169727
 0.57752969 0.49891463 0.63151149 0.56480207]
0    0.521992
1    0.468566
2    0.568393
3    0.356509
4    0.465721
5    0.521697
6    0.577530
7    0.498915
8    0.631511
9    0.564802
dtype: float64


In [69]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([0.79986719, 1.3344244 , 0.89836078, 1.18212726, 1.31928961])

In [70]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [71]:

A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [72]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [73]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


[( 1, 28) ( 1, 35) ( 8, 35) ( 8, 86) (13, 29) (13, 30) (13, 67) (13, 70)
 (27, 44) (27, 56) (27, 72) (27, 76) (28, 35) (28, 84) (29, 70) (30, 67)
 (32, 65) (32, 94) (33, 73) (33, 90) (34, 53) (34, 73) (35, 86) (44, 56)
 (53, 73) (65, 94) (72, 76) (73, 90) (84, 84)]


In [74]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [75]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [76]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [77]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.5689354 ,  0.99618847, -0.97806729, -0.42396264, -0.09665285,
        0.42296347, -0.62452167, -0.55432556,  0.77130193, -0.05849381,
       -0.49329268, -0.38801333, -0.64392686,  0.98001907,  0.39100816,
        0.19666374, -0.7007469 , -0.13426033,  0.36093192, -0.62423628,
       -0.12077611, -0.16479139, -0.29276498, -0.79619472,  0.09269218,
       -0.42993923,  0.44313258, -0.18582763,  0.18368963, -0.69087917,
        0.66483221,  0.36503552,  0.88548231,  0.55967477,  0.25430446,
       -0.61355479, -0.32273899, -0.24937345,  0.22023535, -0.48677717,
       -0.18004323, -0.07363101,  0.10905794,  0.99092588,  0.84744282,
        0.46055673,  0.95814836,  0.52839175,  0.43930725,  0.73937178,
        0.90712087, -0.95588357, -0.42370173,  0.03107509, -0.15746488,
       -0.42661461, -0.83815723,  0.84899677, -0.68946501,  0.75278762,
        0.06143287,  0.54396654, -0.40684209, -0.85914786, -0.62120839,
        0.70459683, -0.51226532, -0.97847227, -0.98338066, -0.48

In [78]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[0.32524812 5.09540879 1.79726106 0.87133599 3.45533687 6.52629273
 0.60585378 2.59384642 0.59207909 3.4530536 ]


In [79]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 5.18400901  4.41929798  0.77073298  1.04390937  0.72519279  6.85606438
   6.1463985   4.24177859  3.56828838  4.49449701]
 [ 3.08450027  3.84917504  7.91270634  9.72545178  9.39701644 15.54119009
  12.5583368   2.41889302  4.84289956  3.08084578]
 [ 5.03097402  1.47330255  4.35987028  2.25630454  1.9072679  11.98258549
   3.45855668  6.63191092  2.1035336   2.16329256]
 [16.31061692 13.48848842 10.674221   10.26150962 10.5779519   3.0511674
   3.48790052 14.10572336 12.90961038 12.35208606]
 [ 4.23554014  9.05331544 12.63109056 11.67667838 11.32560604 20.25690435
  11.46905292  1.57121711  9.90913466  8.73790931]
 [ 4.79587818  2.27109824  5.09400621  2.60625309  2.25398521 12.71636611
   3.36571753  6.68894213  2.8834832   3.01765671]
 [ 0.52218224  2.85373908  6.38609733  6.41708709  6.07917867 14.0119741
   8.48464988  1.62994083  3.68356657  2.74171093]
 [ 0.92858959  3.27539175  6.67631104  6.1421117   5.80033259 14.30151148
   7.76459395  2.31993536  4.0659714   3.30967789]
 [

In [80]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[2 3 6 2 9 2 2 5 3 3]
 [1 6 3 8 1 3 0 5 8 5]
 [5 8 9 7 7 1 6 9 3 2]
 [1 5 9 5 4 3 0 7 1 9]
 [6 3 4 6 5 9 2 4 8 2]
 [4 0 4 6 1 2 5 0 7 3]
 [1 6 1 1 7 7 4 9 4 2]
 [9 1 2 1 4 5 9 1 4 8]
 [1 0 0 4 3 4 4 7 6 5]
 [9 2 3 9 8 6 2 9 0 6]]
[[0 0 0 0 0]
 [0 2 3 6 2]
 [0 1 6 3 8]
 [0 5 8 9 7]
 [0 1 5 9 5]]


E:\anaconda app\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [81]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [93]:
# 82 
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [82]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


In [83]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 0 4]
   [4 3 2]
   [3 0 4]]

  [[0 4 0]
   [3 2 4]
   [0 4 4]]

  [[4 0 2]
   [2 4 4]
   [4 4 1]]

  [[0 2 2]
   [4 4 3]
   [4 1 4]]

  [[2 2 1]
   [4 3 3]
   [1 4 2]]

  [[2 1 4]
   [3 3 2]
   [4 2 4]]

  [[1 4 4]
   [3 2 2]
   [2 4 0]]

  [[4 4 0]
   [2 2 4]
   [4 0 2]]]


 [[[4 3 2]
   [3 0 4]
   [1 4 4]]

  [[3 2 4]
   [0 4 4]
   [4 4 0]]

  [[2 4 4]
   [4 4 1]
   [4 0 0]]

  [[4 4 3]
   [4 1 4]
   [0 0 2]]

  [[4 3 3]
   [1 4 2]
   [0 2 0]]

  [[3 3 2]
   [4 2 4]
   [2 0 2]]

  [[3 2 2]
   [2 4 0]
   [0 2 0]]

  [[2 2 4]
   [4 0 2]
   [2 0 0]]]


 [[[3 0 4]
   [1 4 4]
   [2 0 3]]

  [[0 4 4]
   [4 4 0]
   [0 3 3]]

  [[4 4 1]
   [4 0 0]
   [3 3 0]]

  [[4 1 4]
   [0 0 2]
   [3 0 3]]

  [[1 4 2]
   [0 2 0]
   [0 3 0]]

  [[4 2 4]
   [2 0 2]
   [3 0 3]]

  [[2 4 0]
   [0 2 0]
   [0 3 0]]

  [[4 0 2]
   [2 0 0]
   [3 0 3]]]


 [[[1 4 4]
   [2 0 3]
   [2 3 4]]

  [[4 4 0]
   [0 3 3]
   [3 4 2]]

  [[4 0 0]
   [3 3 0]
   [4 2 3]]

  [[0 0 2]
   [3 0 3]
   [2 3 0]]

  [[0 2 0]
   

In [84]:
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)


[[ 7  6 14 15  6]
 [ 6  5  8  5 17]
 [14  8  5 42 14]
 [15  5 42  3 12]
 [ 6 17 14 12  4]]


In [85]:

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [86]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [87]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [88]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


In [89]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [90]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [91]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.51 s ± 75.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
383 ms ± 31.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
289 ms ± 12 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [92]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 3 4 6 7]


In [94]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 4 1]
 [1 1 1]
 [4 4 0]
 [4 0 4]
 [0 3 4]
 [1 2 3]
 [0 2 1]
 [0 4 0]
 [4 2 4]
 [1 2 2]]
[[1 4 1]
 [4 4 0]
 [4 0 4]
 [0 3 4]
 [1 2 3]
 [0 2 1]
 [0 4 0]
 [4 2 4]
 [1 2 2]]
[[1 4 1]
 [4 4 0]
 [4 0 4]
 [0 3 4]
 [1 2 3]
 [0 2 1]
 [0 4 0]
 [4 2 4]
 [1 2 2]]


In [96]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [97]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)


# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]]
[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]]


In [98]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[1.94137862e-02, 1.90043973e-02, 4.88735056e-03, 1.66674335e-02,
        1.90241432e-02, 7.17494811e-03, 3.83623083e-03, 1.85652441e-03,
        7.08761263e-03, 1.32981526e-02],
       [1.49900658e-01, 1.46739622e-01, 3.77369492e-02, 1.28695105e-01,
        1.46892087e-01, 5.54002929e-02, 2.96208848e-02, 1.43348767e-02,
        5.47259450e-02, 1.02679704e-01],
       [4.66649832e-01, 4.56809336e-01, 1.17477410e-01, 4.00635660e-01,
        4.57283970e-01, 1.72464469e-01, 9.22116094e-02, 4.46253397e-02,
        1.70365183e-01, 3.19648141e-01],
       [1.73382758e-01, 1.69726542e-01, 4.36484830e-02, 1.48855332e-01,
        1.69902891e-01, 6.40788085e-02, 3.42610283e-02, 1.65804505e-02,
        6.32988233e-02, 1.18764590e-01],
       [5.75091662e-04, 5.62964394e-04, 1.44777248e-04, 4.93736870e-04,
        5.63549325e-04, 2.12542406e-04, 1.13640087e-04, 5.49955427e-05,
        2.09955280e-04, 3.93929168e-04],
       [2.85569206e-01, 2.79547254e-01, 7.18910160e-02, 2.45171431e-01,
   

In [99]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [100]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [101]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.20416344  0.2189675 ]
