In [1]:
# import the package
import numpy as np

In [2]:
# create a numpy 2d array
L = [[23,45],[67,89],[56,78]]
a2 = np.array(L)

In [3]:
# ndimm - no of dimensions
print(a2.ndim)
# shape - share as a tuple
print(a2.shape)
# itemsize - returns no of bytes required to store an element
print(a2.itemsize)
# dtype - Data type of numpy array
print(a2.dtype)
# total size of array in bytes
print(a2.size*a2.itemsize)

2
(3, 2)
4
int32
24


In [4]:
for i in a2:
    print(i)
    break

[23 45]


In [5]:
for i in a2:
    print(i)

[23 45]
[67 89]
[56 78]


In [6]:
for i in a2:
    print(type(i))
    break

<class 'numpy.ndarray'>


In [7]:
for i in L:
    print(i)
    print(type(i))

[23, 45]
<class 'list'>
[67, 89]
<class 'list'>
[56, 78]
<class 'list'>


Initializing Array
- np.zeros
- np.ones
- np.eye
- np.full

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.ones((3,4),dtype=np.int8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.ones(2)

array([1., 1.])

In [12]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [13]:
[[False,False],[False,False]]

[[False, False], [False, False]]

In [14]:
np.zeros((2,2),dtype=bool)

array([[False, False],
       [False, False]])

In [15]:
np.full((3,2),9.7)

array([[9.7, 9.7],
       [9.7, 9.7],
       [9.7, 9.7]])

In [16]:
np.diag([7,9,23])

array([[ 7,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 23]])

In [17]:
np.diag([1,1,1])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [18]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

To create a numpy array with in a range of values
- np.arange
- np.linspace

In [19]:
print(np.arange(10))
print(np.arange(2,10))
print(np.arange(2,10,2))
print(np.arange(2,5,0.5))

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6 8]
[2.  2.5 3.  3.5 4.  4.5]


In [20]:
print(np.linspace(5,10,2))
print(np.linspace(5,10,3))
print(np.linspace(5,10,4))

[ 5. 10.]
[ 5.   7.5 10. ]
[ 5.          6.66666667  8.33333333 10.        ]


Basic math operations on Numpy array

In [23]:
a=np.array([1,2,3])
b=np.array([1,1,1])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

[2 3 4]
[0 1 2]
[1 2 3]
[1. 2. 3.]
[1 2 3]
[0 0 0]
[1 2 3]


In [24]:
a+1

array([2, 3, 4])

In [25]:
a+[1]

array([2, 3, 4])

In [28]:
b1=np.full((3,4,2),2)
b2=1
b3=np.array([2,3])
b4=np.array([[1],[2]])

In [29]:
print(b3.shape,b4.shape)
b3 + b4

(2,) (2, 1)


array([[3, 4],
       [4, 5]])

In [30]:
b3

array([2, 3])

In [31]:
b4

array([[1],
       [2]])

In [32]:
b1=np.full((3,4,2),2)
b5=np.full((1,3,1,2),4)

In [33]:
(b1+b5)

array([[[[6, 6],
         [6, 6],
         [6, 6],
         [6, 6]],

        [[6, 6],
         [6, 6],
         [6, 6],
         [6, 6]],

        [[6, 6],
         [6, 6],
         [6, 6],
         [6, 6]]]])

In [38]:
a=np.arange(25)
print(a[:2])
print(a[5:10])
print(a[2:24:5])
print(a[1])
print(a[-1])
print(a[[2,5,9]])
print(a[[24,2,1,6]])

[0 1]
[5 6 7 8 9]
[ 2  7 12 17 22]
1
24
[2 5 9]
[24  2  1  6]


Random

In [40]:
np.random.randint(7,10,(2,2))

array([[9, 9],
       [7, 7]])

In [41]:
np.random.randint(1,10,(2,2))

array([[1, 2],
       [1, 8]])

In [42]:
np.random.randint(4,5)

4

In [44]:
np.random.random((4,5))

array([[0.41315032, 0.02854263, 0.04545718, 0.20038709, 0.04329801],
       [0.93872674, 0.01135334, 0.43244414, 0.71018669, 0.52359409],
       [0.08010388, 0.53210782, 0.23979771, 0.22639634, 0.5255806 ],
       [0.5567194 , 0.86223634, 0.40771779, 0.80165939, 0.2773068 ]])

In [45]:
np.random.randn()

-0.46752855248066627

In [46]:
np.random.randn(2,3)

array([[ 0.25805315,  1.49300615,  0.9572748 ],
       [ 1.5732941 , -0.36499637, -0.31066553]])

In [47]:
np.random.normal(size=(2,3))

array([[-0.59184258, -0.98382876,  1.34691051],
       [-0.69530399, -0.06460197, -1.11639566]])

In [48]:
dir(np.random)

['Lock',
 'RandomState',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bytes',
 'chisquare',
 'choice',
 'dirichlet',
 'division',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'np',
 'operator',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'standard_gamma',
 'standard_normal',
 'standard_t',
 'test',
 'triangular',
 'uniform',
 'vonmises',
 'wald',
 'warnings',
 'weibull',
 'zipf']

In [49]:
a1=np.array([10,20,30,40,50])


In [50]:
np.min(a1)

10

In [51]:
np.max(a1)

50

In [52]:
np.mean(a1)

30.0

In [53]:
np.median(a1)

30.0

In [58]:
np.quantile(a1,0.25)
np.quantile(a1,0.5)
np.quantile(a1,0.75)

40.0

In [56]:
np.sum(a1)

150

In [60]:
np.quantile(a1,0.25)

20.0

In [59]:
np.quantile(a1,0.5)

30.0

In [61]:
np.quantile(a1,0.75)

40.0

In [65]:
x = np.random.randint(3,10,(2,2))
x

array([[9, 6],
       [5, 8]])

In [66]:
y = np.random.randint(3,10,(2,2))
y

array([[4, 6],
       [9, 7]])

In [67]:
x+y

array([[13, 12],
       [14, 15]])

In [68]:
np.sum(x)

28

In [69]:
np.sum(x,axis=0)

array([14, 14])

In [70]:
np.sum(x,axis=1)

array([15, 13])

In [72]:
np.sum(x,axis=1,keepdims=True)

array([[15],
       [13]])

In [73]:
x.shape

(2, 2)

In [76]:
def master():
    '''Hey this is ali
    what do want my help for?'''
    return

In [77]:
help(master)

Help on function master in module __main__:

master()
    Hey this is ali
    what do want my help for?



In [1]:
import master
master.name

'Ali'

In [6]:
bool(' ')

True

In [7]:
if -40:
    print("ali")

ali
