In [1]:
import numpy as np
a = np.arange(7)
b = np.full((7),1)

In [2]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))

[1 2 3 4 5 6 7]
[-1  0  1  2  3  4  5]
[0. 1. 2. 3. 4. 5. 6.]


In [3]:
a3=np.random.randint(100,size=(3,5,4))
a3

array([[[12, 99, 29, 27],
        [54, 31, 38, 76],
        [52, 69, 58, 20],
        [39, 96, 21, 52],
        [15, 42,  0,  4]],

       [[ 4, 76, 42, 48],
        [43, 90, 45, 78],
        [ 1, 48, 47, 19],
        [80, 11, 79, 32],
        [11, 55, 47, 47]],

       [[24, 90, 83, 48],
        [ 0, 53, 14,  6],
        [98, 89, 30, 71],
        [51, 35, 51, 41],
        [66, 24, 59, 85]]])

In [4]:
np.random.seed(23)
a3=np.random.randint(100,size=(3,5,4))
a3

array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]],

       [[12, 21, 48, 41],
        [79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1],
        [43, 15, 86, 83]],

       [[58, 25, 66, 74],
        [35, 96, 56, 13],
        [60, 22, 38, 31],
        [94, 78,  0, 21],
        [ 6, 32, 98, 32]]])

In [5]:
for i in a3:
    print(i)
    break

[[83 40 73 54]
 [31 76 91 39]
 [90 25 51  6]
 [45 12 49 66]
 [75 85 69 64]]


Sclicing or Subsetting

In [6]:
a3[:]

array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]],

       [[12, 21, 48, 41],
        [79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1],
        [43, 15, 86, 83]],

       [[58, 25, 66, 74],
        [35, 96, 56, 13],
        [60, 22, 38, 31],
        [94, 78,  0, 21],
        [ 6, 32, 98, 32]]])

In [7]:
a3[1]

array([[12, 21, 48, 41],
       [79, 90, 62, 57],
       [19, 33, 59, 39],
       [15, 36, 65,  1],
       [43, 15, 86, 83]])

In [8]:
a3[:1] # a3[0] a 5*3 array .. shape(5,4)

array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]]])

In [9]:
print(a3[:2].shape)
a3[:2] # shape(2,5,4)

(2, 5, 4)


array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]],

       [[12, 21, 48, 41],
        [79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1],
        [43, 15, 86, 83]]])

In [10]:
a3[0][2][2] # access element 51 in 1st 5*4 array
a3[0,2,2]

51

In [11]:
a3[1,:,2]  

array([48, 62, 59, 65, 86])

In [12]:
a3[:2,1:3,2] 

array([[91, 51],
       [62, 59]])

In [13]:
a3

array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]],

       [[12, 21, 48, 41],
        [79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1],
        [43, 15, 86, 83]],

       [[58, 25, 66, 74],
        [35, 96, 56, 13],
        [60, 22, 38, 31],
        [94, 78,  0, 21],
        [ 6, 32, 98, 32]]])

In [14]:
a3[[2,1,0]]

array([[[58, 25, 66, 74],
        [35, 96, 56, 13],
        [60, 22, 38, 31],
        [94, 78,  0, 21],
        [ 6, 32, 98, 32]],

       [[12, 21, 48, 41],
        [79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1],
        [43, 15, 86, 83]],

       [[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]]])

In [15]:
a3[:,[3,1]]

array([[[45, 12, 49, 66],
        [31, 76, 91, 39]],

       [[15, 36, 65,  1],
        [79, 90, 62, 57]],

       [[94, 78,  0, 21],
        [35, 96, 56, 13]]])

In [16]:
a3[[2,1],[1,3],[3,2]]

array([13, 65])

In [17]:
a3[[2,1]]

array([[[58, 25, 66, 74],
        [35, 96, 56, 13],
        [60, 22, 38, 31],
        [94, 78,  0, 21],
        [ 6, 32, 98, 32]],

       [[12, 21, 48, 41],
        [79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1],
        [43, 15, 86, 83]]])

In [18]:
a3

array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]],

       [[12, 21, 48, 41],
        [79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1],
        [43, 15, 86, 83]],

       [[58, 25, 66, 74],
        [35, 96, 56, 13],
        [60, 22, 38, 31],
        [94, 78,  0, 21],
        [ 6, 32, 98, 32]]])

In [19]:
a3[2,1,3],a3[1,3,2]

(13, 65)

In [20]:
np.random.seed(0)
a2=np.random.randint(100,size=(5,7))
a2

array([[44, 47, 64, 67, 67,  9, 83],
       [21, 36, 87, 70, 88, 88, 12],
       [58, 65, 39, 87, 46, 88, 81],
       [37, 25, 77, 72,  9, 20, 80],
       [69, 79, 47, 64, 82, 99, 88]])

In [21]:
a2 = np.arange(35).reshape(5,7)
a2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [22]:
a2[:,0::2]

array([[ 0,  2,  4,  6],
       [ 7,  9, 11, 13],
       [14, 16, 18, 20],
       [21, 23, 25, 27],
       [28, 30, 32, 34]])

In [23]:
a2[:,[1,3,5]]

array([[ 1,  3,  5],
       [ 8, 10, 12],
       [15, 17, 19],
       [22, 24, 26],
       [29, 31, 33]])

In [24]:
a2[:,0::2]

array([[ 0,  2,  4,  6],
       [ 7,  9, 11, 13],
       [14, 16, 18, 20],
       [21, 23, 25, 27],
       [28, 30, 32, 34]])

In [25]:
a2[0::2,:]
a2[[0,2,4],:]
a2[1::2,:]
a2[[1,3],:]

array([[ 7,  8,  9, 10, 11, 12, 13],
       [21, 22, 23, 24, 25, 26, 27]])

In [26]:
a2[[1,2,0],[2,4,6]]

array([ 9, 18,  6])

In [27]:
a2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [28]:
a2[[1,2,4],[2,4,0]]

array([ 9, 18, 28])

In [29]:
a2[::2,::2]

array([[ 0,  2,  4,  6],
       [14, 16, 18, 20],
       [28, 30, 32, 34]])

In [30]:
a2 >10

array([[False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [31]:
True + True

2

In [32]:
np.sum(a2>10)

24

In [33]:
True + False

1

In [34]:
print(True + True)
print(True + False)

2
1


In [35]:
a2[a2>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34])

In [36]:
a5=np.array([67,89,23,44,32,78,99])
a5%2==0

array([False, False, False,  True,  True,  True, False])

In [37]:
a5[a5%2==0]  # even no.s

array([44, 32, 78])

In [38]:
a5[a5%2==1]  # odd no.s

array([67, 89, 23, 99])

In [39]:
a5[a5%2==0] = 0
a5

array([67, 89, 23,  0,  0,  0, 99])

In [40]:
a6 = np.array([92,-127,89,-32,2,67])
a6

array([  92, -127,   89,  -32,    2,   67])

In [41]:
a6[a6<0] = [127,32]
a6

array([ 92, 127,  89,  32,   2,  67])

In [42]:
np.abs(a6)  # converting negative number into postive number

array([ 92, 127,  89,  32,   2,  67])

In [43]:
np.mean(a6)

68.16666666666667

Array Manipulation
- reshape
- flatten
- resize

In [45]:
a7 = np.arange(45).reshape((9,5))
a7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [47]:
a7.reshape(1,9,5)
a7.reshape(3,3,5)
a7.reshape(5,3,3)
a7.reshape(3,5,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [48]:
a3.reshape(5,3,-1)

array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6]],

       [[45, 12, 49, 66],
        [75, 85, 69, 64],
        [12, 21, 48, 41]],

       [[79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1]],

       [[43, 15, 86, 83],
        [58, 25, 66, 74],
        [35, 96, 56, 13]],

       [[60, 22, 38, 31],
        [94, 78,  0, 21],
        [ 6, 32, 98, 32]]])

In [49]:
a3

array([[[83, 40, 73, 54],
        [31, 76, 91, 39],
        [90, 25, 51,  6],
        [45, 12, 49, 66],
        [75, 85, 69, 64]],

       [[12, 21, 48, 41],
        [79, 90, 62, 57],
        [19, 33, 59, 39],
        [15, 36, 65,  1],
        [43, 15, 86, 83]],

       [[58, 25, 66, 74],
        [35, 96, 56, 13],
        [60, 22, 38, 31],
        [94, 78,  0, 21],
        [ 6, 32, 98, 32]]])

In [51]:
a7.resize(5,9)

In [52]:
a7

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [53]:
help(a7.resize)

Help on built-in function resize:

resize(...) method of numpy.ndarray instance
    a.resize(new_shape, refcheck=True)
    
    Change shape and size of array in-place.
    
    Parameters
    ----------
    new_shape : tuple of ints, or `n` ints
        Shape of resized array.
    refcheck : bool, optional
        If False, reference count will not be checked. Default is True.
    
    Returns
    -------
    None
    
    Raises
    ------
    ValueError
        If `a` does not own its own data or references or views to it exist,
        and the data memory must be changed.
        PyPy only: will always raise if the data memory must be changed, since
        there is no reliable way to determine if references or views to it
        exist.
    
    SystemError
        If the `order` keyword argument is specified. This behaviour is a
        bug in NumPy.
    
    See Also
    --------
    resize : Return a new array with the specified shape.
    
    Notes
    -----
    This realloca

In [54]:
help(np.resize)

Help on function resize in module numpy:

resize(a, new_shape)
    Return a new array with the specified shape.
    
    If the new array is larger than the original array, then the new
    array is filled with repeated copies of `a`.  Note that this behavior
    is different from a.resize(new_shape) which fills with zeros instead
    of repeated copies of `a`.
    
    Parameters
    ----------
    a : array_like
        Array to be resized.
    
    new_shape : int or tuple of int
        Shape of resized array.
    
    Returns
    -------
    reshaped_array : ndarray
        The new array is formed from the data in the old array, repeated
        if necessary to fill out the required number of elements.  The
        data are repeated in the order that they are stored in memory.
    
    See Also
    --------
    ndarray.resize : resize an array in-place.
    
    Notes
    -----
    i.e. it does not apply interpolation/extrapolation.
    It fills the return array with the required 

In [55]:
np.resize(a7,(5,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44,  0,  1,  2,  3,  4]])

In [56]:
a7.shape

(5, 9)

In [57]:
a7.flatten()   # it displays any dimenstion to 1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [58]:
a7

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [61]:
a7.reshape(5*9)
a7.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [62]:
a7.reshape(5*9)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [63]:
a7.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [64]:
np.reshape(a7,(5*9))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [65]:
np.swapaxes(a7,0,1)

array([[ 0,  9, 18, 27, 36],
       [ 1, 10, 19, 28, 37],
       [ 2, 11, 20, 29, 38],
       [ 3, 12, 21, 30, 39],
       [ 4, 13, 22, 31, 40],
       [ 5, 14, 23, 32, 41],
       [ 6, 15, 24, 33, 42],
       [ 7, 16, 25, 34, 43],
       [ 8, 17, 26, 35, 44]])

In [66]:
a7.shape

(5, 9)

In [67]:
a3.shape

(3, 5, 4)

In [68]:
np.swapaxes(a3,0,2).shape

(4, 5, 3)

Log Functions

In [69]:
import math
math.log(2)

0.6931471805599453

In [70]:
np.log(2)

0.6931471805599453

In [71]:
np.log([2,4,6])

array([0.69314718, 1.38629436, 1.79175947])

In [72]:
np.log2(2)

1.0

In [73]:
np.log1p(1)  # np.log1p(x)=np.log(1+x)

0.6931471805599453

In [74]:
np.log1p(0)

0.0

exponential

In [75]:
np.exp(1)

2.718281828459045

In [76]:
np.log(np.exp(1))

1.0

In [80]:
np.exp2(2)

4.0

In [82]:
np.expm1(2)

6.38905609893065

In [83]:
np.exp(2)-1

6.38905609893065